extends Node

var upgrades = {
	UPGRADE_DB.upg_ids.heater_efficiency: 0,
	UPGRADE_DB.upg_ids.heater_controller: 0,
	UPGRADE_DB.upg_ids.skills_hp_up: 0,
	UPGRADE_DB.upg_ids.skills_energy_up: 0,
	UPGRADE_DB.upg_ids.skills_temp_up: 0,
	UPGRADE_DB.upg_ids.skills_temp_down: 0,
	UPGRADE_DB.upg_ids.freq_closer_static: 0,
	UPGRADE_DB.upg_ids.freq_closer_relic: 0,
	UPGRADE_DB.upg_ids.freq_: 0,
	UPGRADE_DB.upg_ids.light_eye: 0,
	UPGRADE_DB.upg_ids.light_core: 0,
	UPGRADE_DB.upg_ids.lightstick: 0,
	UPGRADE_DB.upg_ids.lightstick_glow: 0,
	UPGRADE_DB.upg_ids.hull_defense: 0,
	UPGRADE_DB.upg_ids.hull_insulation: 0,
	UPGRADE_DB.upg_ids.hull_depth_max: 0,
	UPGRADE_DB.upg_ids.static_tank: 0,
	UPGRADE_DB.upg_ids.static_insulation: 0,
	UPGRADE_DB.upg_ids.motor_turbo_boost: 0,
	UPGRADE_DB.upg_ids.motor_boost_efficiency: 0,
	UPGRADE_DB.upg_ids.batteries: 0,
}

#var upgrades = {
	#UPGRADE_DB.upg_ids.heater_efficiency: null,
	#UPGRADE_DB.upg_ids.heater_controller: null,
	#UPGRADE_DB.upg_ids.skills_hp_up: null,
	#UPGRADE_DB.upg_ids.skills_energy_up: null,
	#UPGRADE_DB.upg_ids.skills_temp_up: null,
	#UPGRADE_DB.upg_ids.skills_temp_down: null,
	#UPGRADE_DB.upg_ids.freq_closer_static: null,
	#UPGRADE_DB.upg_ids.freq_closer_relic: null,
	#UPGRADE_DB.upg_ids.freq_: null,
	#UPGRADE_DB.upg_ids.light_eye: null,
	#UPGRADE_DB.upg_ids.light_core: null,
	#UPGRADE_DB.upg_ids.lightstick: null,
	#UPGRADE_DB.upg_ids.lightstick_glow: null,
	#UPGRADE_DB.upg_ids.hull_defense: 0,
	#UPGRADE_DB.upg_ids.hull_insulation: null,
	#UPGRADE_DB.upg_ids.hull_depth_max: 0,
	#UPGRADE_DB.upg_ids.static_tank: 0,
	#UPGRADE_DB.upg_ids.static_insulation: null,
	#UPGRADE_DB.upg_ids.motor_turbo_boost: null,
	#UPGRADE_DB.upg_ids.motor_boost_efficiency: null,
	#UPGRADE_DB.upg_ids.batteries: 0,
#}
